# Generated by Django 4.2.4 on 2023-08-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
    ]
